/**
 * DEMO ONLY — sample records from the Claude Design handoff (design/claude-design/project/mock-data.js).
 * They let the UI be reviewed before the CMS/catalog APIs exist. Every record is flagged
 * `isDemo: true` and rendered with a «نمونه نمایشی» label. Replace with API repositories
 * (EPIC-03/06/09/10/16); never present these as real projects, courses or research.
 */
import type { DemoCourse, DemoEntry, DemoProject, SectorKey } from './types';

export const sectors: { value: 'all' | SectorKey; label: string }[] = [
  { value: 'all', label: 'همه' },
  { value: 'mining', label: 'معدنی' },
  { value: 'industry', label: 'صنعتی' },
  { value: 'energy', label: 'انرژی' },
  { value: 'agri', label: 'کشاورزی و غذایی' },
  { value: 'infra', label: 'خدمات و زیرساخت' },
];

export const demoProjects: DemoProject[] = [
  {
    id: 'p1',
    isDemo: true,
    title: 'طرح نمونه واحد فرآوری سنگ آهن',
    sector: 'mining',
    sectorLabel: 'معدنی',
    location: 'کرمان',
    stage: 'ایده اولیه',
    service: 'مطالعات امکان‌سنجی',
  },
  {
    id: 'p2',
    isDemo: true,
    title: 'طرح نمونه تولید قطعات صنعتی',
    sector: 'industry',
    sectorLabel: 'صنعتی',
    location: 'اصفهان',
    stage: 'طرح توجیهی',
    service: 'مشاوره تأمین مالی',
  },
  {
    id: 'p3',
    isDemo: true,
    title: 'طرح نمونه نیروگاه خورشیدی کوچک',
    sector: 'energy',
    sectorLabel: 'انرژی',
    location: 'یزد',
    stage: 'مطالعه بازار',
    service: 'امکان‌سنجی فنی و مالی',
  },
  {
    id: 'p4',
    isDemo: true,
    title: 'طرح نمونه مجتمع بسته‌بندی محصولات کشاورزی',
    sector: 'agri',
    sectorLabel: 'کشاورزی و غذایی',
    location: 'خراسان رضوی',
    stage: 'ایده اولیه',
    service: 'طرح توجیهی',
  },
  {
    id: 'p5',
    isDemo: true,
    title: 'طرح نمونه توسعه معدن سنگ ساختمانی',
    sector: 'mining',
    sectorLabel: 'معدنی',
    location: 'لرستان',
    stage: 'مطالعه فنی',
    service: 'مشاوره سرمایه‌گذاری صنعتی',
  },
  {
    id: 'p6',
    isDemo: true,
    title: 'طرح نمونه مرکز لجستیک منطقه‌ای',
    sector: 'infra',
    sectorLabel: 'خدمات و زیرساخت',
    location: 'قزوین',
    stage: 'طرح توجیهی',
    service: 'مشاوره پروژه',
  },
];

export const demoCourses: DemoCourse[] = [
  {
    id: 'c1',
    isDemo: true,
    title: 'مبانی امکان‌سنجی طرح‌های صنعتی',
    category: 'امکان‌سنجی',
    instructor: 'مدرس نمونه',
    level: 'مقدماتی',
    duration: '۱۲ ساعت',
    free: false,
  },
  {
    id: 'c2',
    isDemo: true,
    title: 'آشنایی با روش‌های تأمین مالی پروژه',
    category: 'تأمین مالی',
    instructor: 'مدرس نمونه',
    level: 'متوسط',
    duration: '۸ ساعت',
    free: false,
  },
  {
    id: 'c3',
    isDemo: true,
    title: 'اقتصاد برای مدیران',
    category: 'اقتصاد',
    instructor: 'مدرس نمونه',
    level: 'مقدماتی',
    duration: '۶ ساعت',
    free: true,
  },
  {
    id: 'c4',
    isDemo: true,
    title: 'ارزیابی مالی طرح‌های سرمایه‌گذاری',
    category: 'سرمایه‌گذاری',
    instructor: 'مدرس نمونه',
    level: 'پیشرفته',
    duration: '۱۶ ساعت',
    free: false,
  },
  {
    id: 'c5',
    isDemo: true,
    title: 'تدوین طرح توجیهی',
    category: 'امکان‌سنجی',
    instructor: 'مدرس نمونه',
    level: 'متوسط',
    duration: '۱۰ ساعت',
    free: false,
  },
  {
    id: 'c6',
    isDemo: true,
    title: 'آشنایی با بازار سرمایه',
    category: 'سرمایه‌گذاری',
    instructor: 'مدرس نمونه',
    level: 'مقدماتی',
    duration: '۴ ساعت',
    free: true,
  },
];

export const demoResearch: DemoEntry[] = [
  {
    id: 'r1',
    isDemo: true,
    title: 'نمونه: بررسی زنجیره ارزش فولاد',
    summary: 'مطالعه‌ای نمونه درباره حلقه‌های زنجیره ارزش و گلوگاه‌های آن.',
    category: 'صنعتی',
    date: '2026-08-03',
  },
  {
    id: 'r2',
    isDemo: true,
    title: 'نمونه: الگوهای تأمین مالی طرح‌های معدنی',
    summary: 'مرور نمونه روش‌های رایج تأمین مالی در طرح‌های معدنی.',
    category: 'مالی',
    date: '2026-07-19',
  },
  {
    id: 'r3',
    isDemo: true,
    title: 'نمونه: شاخص‌های توسعه منطقه‌ای',
    summary: 'چارچوبی نمونه برای سنجش آمادگی مناطق برای سرمایه‌گذاری.',
    category: 'توسعه‌ای',
    date: '2026-06-05',
  },
  {
    id: 'r4',
    isDemo: true,
    title: 'نمونه: تحلیل بازار مصالح ساختمانی',
    summary: 'بررسی نمونه عرضه و تقاضا در بازار مصالح.',
    category: 'اقتصادی',
    date: '2026-04-29',
  },
];

export const demoKnowledge: DemoEntry[] = [
  {
    id: 'k1',
    isDemo: true,
    title: 'امکان‌سنجی چیست؟',
    summary: 'تعریف، مراحل و خروجی‌های یک مطالعه امکان‌سنجی.',
    category: 'امکان‌سنجی',
    date: '2026-08-24',
  },
  {
    id: 'k2',
    isDemo: true,
    title: 'طرح توجیهی',
    summary: 'اجزای اصلی طرح توجیهی و تفاوت آن با امکان‌سنجی.',
    category: 'امکان‌سنجی',
    date: '2026-08-11',
  },
  {
    id: 'k3',
    isDemo: true,
    title: 'نرخ بازده داخلی (IRR)',
    summary: 'مفهوم و کاربرد نرخ بازده داخلی در ارزیابی طرح‌ها.',
    category: 'مالی',
    date: '2026-07-23',
  },
  {
    id: 'k4',
    isDemo: true,
    title: 'تأمین مالی پروژه',
    summary: 'آشنایی با ساختار تأمین مالی مبتنی بر پروژه.',
    category: 'تأمین مالی',
    date: '2026-07-09',
  },
  {
    id: 'k5',
    isDemo: true,
    title: 'ارزش فعلی خالص (NPV)',
    summary: 'روش محاسبه و تفسیر ارزش فعلی خالص.',
    category: 'مالی',
    date: '2026-06-25',
  },
  {
    id: 'k6',
    isDemo: true,
    title: 'توکنایز کردن دارایی',
    summary: 'مفهوم پایه‌ای بازنمایی دیجیتال دارایی‌های واقعی.',
    category: 'فناوری',
    date: '2026-06-12',
  },
];

export const demoArticles: DemoEntry[] = [
  {
    id: 'a1',
    isDemo: true,
    title: 'نمونه مقاله: نقش امکان‌سنجی در کاهش ریسک',
    summary: 'چرا مطالعه پیش از اجرا اهمیت دارد.',
    category: 'امکان‌سنجی',
    date: '2026-09-09',
  },
  {
    id: 'a2',
    isDemo: true,
    title: 'نمونه مقاله: انتخاب روش تأمین مالی',
    summary: 'معیارهای انتخاب روش مناسب تأمین مالی.',
    category: 'تأمین مالی',
    date: '2026-08-26',
  },
  {
    id: 'a3',
    isDemo: true,
    title: 'نمونه مقاله: آموزش سرمایه‌گذاری برای مدیران',
    summary: 'مفاهیمی که مدیران باید بشناسند.',
    category: 'آموزش',
    date: '2026-08-18',
  },
  {
    id: 'a4',
    isDemo: true,
    title: 'نمونه مقاله: داده در تصمیم‌گیری صنعتی',
    summary: 'استفاده از داده در مطالعات صنعتی.',
    category: 'پژوهش',
    date: '2026-08-01',
  },
  {
    id: 'a5',
    isDemo: true,
    title: 'نمونه مقاله: خطاهای رایج در طرح توجیهی',
    summary: 'اشتباهاتی که در تدوین طرح توجیهی تکرار می‌شوند.',
    category: 'امکان‌سنجی',
    date: '2026-07-20',
  },
  {
    id: 'a6',
    isDemo: true,
    title: 'نمونه مقاله: مسیر از پژوهش تا پروژه',
    summary: 'پیوند مطالعات پژوهشی با تعریف پروژه.',
    category: 'پژوهش',
    date: '2026-07-02',
  },
];
